### ISSUE TITLE
Error when using projectdiscovery/chaos-client: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 0xSebin** [projectdiscovery/chaos-client#153]
### chaos-client version:
v0.4.0

### Current Behavior:
I got some errors and scan whole terminal freezed while scanning for subdomains

### Command i used
chaos -d test.com | httpx -o live.txt

### Error i got 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6b4028]

goroutine 6 [running]:
github.com/projectdiscovery/chaos-client/pkg/chaos.(*Client).do(0xc00007a240, 0xc0000f05d0)
        /home/sebin/go/pkg/mod/github.com/projectdiscovery/chaos-client@v0.4.0/pkg/chaos/chaos.go:37 +0x148
github.com/projectdiscovery/chaos-client/pkg/chaos.(*Client).GetSubdomains.func1(0xc000090120)
        /home/sebin/go/pkg/mod/github.com/projectdiscovery/chaos-client@v0.4.0/pkg/chaos/chaos.go:120 +0x1bb
created by github.com/projectdiscovery/chaos-client/pkg/chaos.(*Client).GetSubdomains
        /home/sebin/go/pkg/mod/github.com/projectdiscovery/chaos-client@v0.4.0/pkg/chaos/chaos.go:111 +0xe5
 
Screenshot: 
![image](https://user-images.githubusercontent.com/56429311/222668372-f6c94b47-8461-4774-b27d-f4849fe7804f.png)

**Comment by ehsandeep** [comment]
@0xSebin fixed in latest release - https://github.com/projectdiscovery/chaos-client/releases/tag/v0.5.0
