### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by 0xPugazh** [projectdiscovery/chaos-client#164]
```
root@ubuntu-do:~# chaos -d target.com -key API_KEY -o output.txt

        __                    
  _____/ /_  ____ _____  _____
 / ___/ __ \/ __  / __ \/ ___/
/ /__/ / / / /_/ / /_/ (__  ) 
\___/_/ /_/\__,_/\____/____/  v0.4.0

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6bbc9d]

goroutine 6 [running]:
github.com/projectdiscovery/chaos-client/pkg/chaos.(*Client).do(0xc000036380, 0xc00015c1b0)
        /root/go/pkg/mod/github.com/projectdiscovery/chaos-client@v0.4.0/pkg/chaos/chaos.go:37 +0x13d
github.com/projectdiscovery/chaos-client/pkg/chaos.(*Client).GetSubdomains.func1(0xc000102120)
        /root/go/pkg/mod/github.com/projectdiscovery/chaos-client@v0.4.0/pkg/chaos/chaos.go:120 +0x1bb
created by github.com/projectdiscovery/chaos-client/pkg/chaos.(*Client).GetSubdomains
        /root/go/pkg/mod/github.com/projectdiscovery/chaos-client@v0.4.0/pkg/chaos/chaos.go:111 +0xe5
```

**Comment by ehsandeep** [comment]
@0xPugazh it was fixed in last release - https://github.com/projectdiscovery/chaos-client/issues/153, make sure to update to the latest version.

**Comment by ehsandeep** [comment]
Closing this issue as this is already fixed.
